# Generated by Django 4.0.2 on 2024-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(default=None),
        ),
    ]
